/*
 * Single source of truth for the 87 CDSL ISIN Master field definitions.
 *
 * Kept in its own module so both IsinMaster.jsx (table rendering) and
 * parseCdslFile.js (file parsing) can import it without creating a
 * circular dependency (IsinMaster → UploadModal → parseCdslFile → IsinMaster
 * would be circular; importing from this leaf module breaks the cycle).
 */
export const ISIN_COLUMNS = [
  { header: 'ISIN Numeric Code',                field: 'isinNumericCode'               },
  { header: 'ISIN Alpha Code',                  field: 'isinAlphaCode'                 },
  { header: 'ISIN Short Name',                  field: 'isinShortName'                 },
  { header: 'ISIN Description',                 field: 'isinDescription'               },
  { header: 'Issuer ID',                        field: 'issuerId'                      },
  { header: 'Issuer Name',                      field: 'issuerName'                    },
  { header: 'Issuer Address 1',                field: 'issuerAddress1'                },
  { header: 'Issuer Address 2',                field: 'issuerAddress2'                },
  { header: 'Issuer Address 3',                field: 'issuerAddress3'                },
  { header: 'Issuer City',                      field: 'issuerCity'                    },
  { header: 'Issuer State',                     field: 'issuerState'                   },
  { header: 'Issuer Country',                   field: 'issuerCountry'                 },
  { header: 'Issuer Zip Code',                  field: 'issuerZipCode'                 },
  { header: 'Issuer Phone 1',                   field: 'issuerPhone1'                  },
  { header: 'Issuer Phone 2',                   field: 'issuerPhone2'                  },
  { header: 'Issuer Fax',                       field: 'issuerFax'                     },
  { header: 'Issuer Email',                     field: 'issuerEmail'                   },
  { header: 'Issuer Contact Person Name',       field: 'issuerContactPersonName'       },
  { header: 'Contact Person Designation',       field: 'contactPersonDesignation'      },
  { header: 'Contact Person Address 1',        field: 'contactPersonAddress1'         },
  { header: 'Contact Person Address 2',        field: 'contactPersonAddress2'         },
  { header: 'Contact Person Address 3',        field: 'contactPersonAddress3'         },
  { header: 'Contact Person City',              field: 'contactPersonCity'             },
  { header: 'Contact Person State',             field: 'contactPersonState'            },
  { header: 'Contact Person Country',           field: 'contactPersonCountry'          },
  { header: 'Contact Person Zip Code',          field: 'contactPersonZipCode'          },
  { header: 'Contact Person Phone 1',           field: 'contactPersonPhone1'           },
  { header: 'Contact Person Phone 2',           field: 'contactPersonPhone2'           },
  { header: 'Contact Person Fax',               field: 'contactPersonFax'              },
  { header: 'Contact Person Email',             field: 'contactPersonEmail'            },
  { header: 'RTA ID',                           field: 'rtaId'                         },
  { header: 'RTA Name',                         field: 'rtaName'                       },
  { header: 'SEBI Registration From Date',      field: 'sebiRegistrationFromDate'      },
  { header: 'SEBI Registration To Date',        field: 'sebiRegistrationToDate'        },
  { header: 'RTA Address 1',                   field: 'rtaAddress1'                   },
  { header: 'RTA Address 2',                   field: 'rtaAddress2'                   },
  { header: 'RTA Address 3',                   field: 'rtaAddress3'                   },
  { header: 'RTA City',                         field: 'rtaCity'                       },
  { header: 'RTA State',                        field: 'rtaState'                      },
  { header: 'RTA Country',                      field: 'rtaCountry'                    },
  { header: 'RTA Zip Code',                     field: 'rtaZipCode'                    },
  { header: 'RTA Phone 1',                      field: 'rtaPhone1'                     },
  { header: 'RTA Phone 2',                      field: 'rtaPhone2'                     },
  { header: 'RTA Fax',                          field: 'rtaFax'                        },
  { header: 'RTA Email',                        field: 'rtaEmail'                      },
  { header: 'ISIN Share Name',                  field: 'isinShareName'                 },
  { header: 'ISIN Second Name',                 field: 'isinSecondName'                },
  { header: 'ISIN Last Name',                   field: 'isinLastName'                  },
  { header: 'ISIN Address 1',                  field: 'isinAddress1'                  },
  { header: 'ISIN Address 2',                  field: 'isinAddress2'                  },
  { header: 'ISIN Address 3',                  field: 'isinAddress3'                  },
  { header: 'ISIN City',                        field: 'isinCity'                      },
  { header: 'ISIN State',                       field: 'isinState'                     },
  { header: 'ISIN Country',                     field: 'isinCountry'                   },
  { header: 'ISIN Zip Code',                    field: 'isinZipCode'                   },
  { header: 'ISIN Phone 1',                     field: 'isinPhone1'                    },
  { header: 'ISIN Phone 2',                     field: 'isinPhone2'                    },
  { header: 'ISIN Fax',                         field: 'isinFax'                       },
  { header: 'ISIN Email',                       field: 'isinEmail'                     },
  { header: 'Security Type',                    field: 'securityType'                  },
  { header: 'Security Type Description',        field: 'securityTypeDescription'       },
  { header: 'Market Type',                      field: 'marketType'                    },
  { header: 'Market Type Description',          field: 'marketTypeDescription'         },
  { header: 'ISIN Status',                      field: 'isinStatus'                    },
  { header: 'ISIN Status Description',          field: 'isinStatusDescription'         },
  { header: 'Hold Demat Flag',                  field: 'holdDematFlag'                 },
  { header: 'Hold Remat Flag',                  field: 'holdRematFlag'                 },
  { header: 'Expiry Date',                      field: 'expiryDate'                    },
  { header: 'Market Lot',                       field: 'marketLot'                     },
  { header: 'CFI Code',                         field: 'cfiCode'                       },
  { header: 'Par Value',                        field: 'parValue'                      },
  { header: 'Paidup Value',                     field: 'paidupValue'                   },
  { header: 'Redemption Price',                 field: 'redemptionPrice'               },
  { header: 'Redemption Date',                  field: 'redemptionDate'                },
  { header: 'Close Price',                      field: 'closePrice'                    },
  { header: 'Close Date',                       field: 'closeDate'                     },
  { header: 'Issue Date',                       field: 'issueDate'                     },
  { header: 'Close Price Decimal Indicator',    field: 'closePriceDecimalIndicator'    },
  { header: 'Conversion Date',                  field: 'conversionDate'                },
  { header: 'Distinct Range Exists',            field: 'distinctRangeExists'           },
  { header: 'ISIN Decimal Code',                field: 'isinDecimalCode'               },
  { header: 'ISIN Decimal Code Description',    field: 'isinDecimalCodeDescription'    },
  { header: 'ISIN Suspension Flag',             field: 'isinSuspensionFlag'            },
  { header: 'ISIN Suspension Flag Description', field: 'isinSuspensionFlagDescription' },
  { header: 'Money Due Date',                   field: 'moneyDueDate'                  },
  { header: 'ISIN Complete',                    field: 'isinComplete'                  },
  { header: 'Remarks',                          field: 'remarks'                       },
];
