export const NSDL_COLUMNS = [
  { field: 'recordType',             start: 0,   end: 2   },
  { field: 'lineNumber',             start: 2,   end: 9   },
  { field: 'isin',                   start: 9,   end: 21  },
  { field: 'nationalSecurityCode',   start: 21,  end: 30  },
  { field: 'bookingBasis',           start: 30,  end: 32  },
  { field: 'isinShortName',          start: 32,  end: 172 },
  { field: 'companyCode',            start: 172, end: 180 },
  { field: 'issuerName',             start: 180, end: 320 },
  { field: 'securityType',           start: 320, end: 322 },
  { field: 'securitySubType',        start: 322, end: 324 },
  { field: 'issueDateNsdl',          start: 324, end: 332, type: 'date'    },
  { field: 'maturityDate',           start: 332, end: 340, type: 'date'    },
  { field: 'convertDateNsdl',        start: 340, end: 348, type: 'date'    },
  { field: 'faceValue',              start: 348, end: 363, type: 'decimal' },
  { field: 'convertAmount',          start: 363, end: 378, type: 'decimal' },
  { field: 'shareRegistrarCode',     start: 378, end: 386 },
  { field: 'shareRegistrarName',     start: 386, end: 526 },
  { field: 'isinStatusNsdl',         start: 526, end: 528 },
  { field: 'securityRemark',         start: 528, end: 588 },
  { field: 'decimalAllowed',         start: 588, end: 589, type: 'flag'    },
  { field: 'isinActivationDateNsdl', start: 589, end: 597, type: 'date'    },
  { field: 'lastUpdateDate',         start: 597, end: 605, type: 'date'    },
];
